### ISSUE TITLE
Automatic Complete would not work correctly when adding quotes

### ISSUE THREAD

**Issue by skybird23333** [CoreCoder-Devs/CoreCoder-One#3]
![a](https://user-images.githubusercontent.com/58811224/99540434-7069cc80-29ea-11eb-97cb-c561a137c061.gif)

**Comment by Hanprogramer** [comment]
Apparently this bug happens when CC doesn't know what to display on the autocomplete list

**Comment by Hanprogramer** [comment]
Fixed
